src/Entity/Painting.php
<?php

namespace App\Entity;

use App\Repository\PaintingRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PaintingRepository::class)]
class Painting
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $painting_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $paintingURL = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $paintingDate = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $painterName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $painterDescription = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $smallPaintingUrl = null;

    #[ORM\ManyToOne]
    private ?ArtMovment $movmentKey = null;

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getPaintingName(): ?string
    {
        return $this->painting_name;
    }

    public function setPaintingName(?string $painting_name): self
    {
        $this->painting_name = $painting_name;

        return $this;
    }

    public function getPaintingURL(): ?string
    {
        return $this->paintingURL;
    }

    public function setPaintingURL(?string $paintingURL): self
    {
        $this->paintingURL = $paintingURL;

        return $this;
    }

    public function getPaintingDate(): ?string
    {
        return $this->paintingDate;
    }

    public function setPaintingDate(?string $paintingDate): self
    {
        $this->paintingDate = $paintingDate;

        return $this;
    }

    public function getPainterName(): ?string
    {
        return $this->painterName;
    }

    public function setPainterName(?string $painterName): self
    {
        $this->painterName = $painterName;

        return $this;
    }

    public function getPainterDescription(): ?string
    {
        return $this->painterDescription;
    }

    public function setPainterDescription(?string $painterDescription): self
    {
        $this->painterDescription = $painterDescription;

        return $this;
    }

    public function getSmallPaintingUrl(): ?string
    {
        return $this->smallPaintingUrl;
    }

    public function setSmallPaintingUrl(?string $smallPaintingUrl): self
    {
        $this->smallPaintingUrl = $smallPaintingUrl;

        return $this;
    }

    public function getMovmentKey(): ?artMovment
    {
        return $this->movmentKey;
    }

    public function setMovmentKey(?artMovment $movmentKey): self
    {
        $this->movmentKey = $movmentKey;

        return $this;
    }
}

src/Form/PaintingType.php
<?php

namespace App\Form;

use App\Entity\ArtMovment;
use App\Entity\Painting;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PaintingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('painting_name')
            ->add('paintingURL')
            ->add('paintingDate')
            ->add('painterName')
            ->add('painterDescription')
            ->add('smallPaintingUrl')
            ->add('movmentKey', null, [
                'choice_label' => 'art_movment_name',
                'label' => 'Mouvement Artistique'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Painting::class,
        ]);
    }
}

            // ->add('partner', EntityType::class, [
            //     'required' => false,
            //     'mapped' => false,
            //     'class' => Partner::class,
            //     'choice_label' => 'name',
            //     'choice_value' => 'id',
            //     'label' => 'Entreprise',
            //     'multiple' => false,
            //     'expanded' => false,
            //     'placeholder' => 'Ex : Externatic',
            // ]);

src/Controller/PaintingController.php
<?php

namespace App\Controller;

use App\Entity\ArtMovment;
use App\Entity\Painting;
use App\Form\PaintingType;
use App\Repository\PaintingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

#[Route('/painting')]
class PaintingController extends AbstractController
{
    #[Route('/', name: 'app_painting_index', methods: ['GET'])]
    #[IsGranted('ROLE_ADMIN')]
    public function index(PaintingRepository $paintingRepository): Response
    {
        return $this->render('painting/index.html.twig', [
            'paintings' => $paintingRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_painting_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function new(Request $request, PaintingRepository $paintingRepository): Response
    {
        $painting = new Painting();
        $form = $this->createForm(PaintingType::class, $painting);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $paintingRepository->save($painting, true);

            return $this->redirectToRoute('app_painting_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('painting/new.html.twig', [
            'painting' => $painting,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_painting_show', methods: ['GET'])]
    #[IsGranted('ROLE_ADMIN')]
    public function show(Painting $painting): Response
    {
        return $this->render('painting/show.html.twig', [
            'painting' => $painting,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_painting_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function edit(Request $request, Painting $painting, PaintingRepository $paintingRepository): Response
    {
        $form = $this->createForm(PaintingType::class, $painting);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $paintingRepository->save($painting, true);

            return $this->redirectToRoute('app_painting_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('painting/edit.html.twig', [
            'painting' => $painting,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_painting_delete', methods: ['POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function delete(Request $request, Painting $painting, PaintingRepository $paintingRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $painting->getId(), $request->request->get('_token'))) {
            $paintingRepository->remove($painting, true);
        }

        return $this->redirectToRoute('app_painting_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/quizz/{id}', name: 'app_painting_quizz', methods: ['GET', 'POST'])]
    public function quizz(Painting $painting, PaintingRepository $paintingRepository, Request $request): Response
    {
        $movmentId = $painting->getMovmentKey()->getId();

        if ($request->isMethod('POST')) {
            $selectedAnswer = $request->request->get('selectedAnswer');
            $verificationResult = $this->verifyAnswer($selectedAnswer, $painting->getPaintingName());
        } else {
            $verificationResult = null;
        }

        return $this->render('painting/quizz.html.twig', [
            'painting' => $painting,
            'paintings' => $paintingRepository->findAnswers($movmentId),
            'verificationResult' => $verificationResult,
        ]);
    }

    #[Route('/painting/random', name: 'app_painting_random', methods: ['GET'])]
    public function random(PaintingRepository $paintingRepository): Response
    {
        $paintings = $paintingRepository->findAll();
        $randomIndex = rand(0, count($paintings) - 1);
        $randomPainting = $paintings[$randomIndex];

        return $this->redirectToRoute('app_painting_quizz', ['id' => $randomPainting->getId()]);
    }

    private function verifyAnswer(string $selectedAnswer, string $realAnswer): string
    {
        if ($selectedAnswer === $realAnswer) {
            return 'Correct answer!';
        }
        return 'Wrong answer.';
    }

    #[Route('/painting/random', name: 'app_random_painting', methods: ['GET', 'POST'])]
    public function randomPainting(PaintingRepository $paintingRepository)
    {
        $paintings = $paintingRepository->findAll();
        $randomPainting = $paintings[array_rand($paintings)];

        return $this->redirectToRoute('app_painting_show', [
            'id' => $randomPainting->getId(),
        ]);
    }
}

templates/painting/_delete_form.html.twig
<form method="post" action="{{ path('app_painting_delete', {'id': painting.id}) }}" onsubmit="return confirm('Etes vous sûr de vouloir supprimer cette peinture ?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ painting.id) }}">
	<button class="btnDelete mt-3">Delete</button>
</form>

templates/painting/_form.html.twig
{{ form_start(form, {'attr': {'class': 'd-flex flex-column'}}) }}
{# {{ form_widget(form) }} #}
{{ form_row(form.painting_name, {'attr': {'class': 'd-flex flex-column mb-2'}}) }}
{{ form_row(form.paintingURL, {'attr': {'class': 'd-flex flex-column mb-2'}}) }}
{{ form_row(form.paintingDate, {'attr': {'class': 'd-flex flex-column mb-2'}}) }}
{{ form_row(form.painterName, {'attr': {'class': 'd-flex flex-column mb-2'}}) }}
{{ form_row(form.painterDescription, {'attr': {'class': 'd-flex flex-column mb-2'}}) }}
{{ form_row(form.smallPaintingUrl, {'attr': {'class': 'd-flex flex-column mb-2'}}) }}
{{ form_row(form.movmentKey, {'attr': {'class': 'd-flex flex-column mb-2'}}) }}
<button class="btnAdminForm mt-3">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/painting/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer la peinture
{% endblock %}

{% block body %}

	<body class="homeImage">

		<h1 class="editTitle">Editer la peinture</h1>

		<div class="alertContainer">
			<div>

				{{ include('painting/_form.html.twig', {'button_label': 'Modifier'}) }}

				{{ include('painting/_delete_form.html.twig') }}

				<a class="returnText mt-3" href="{{ path('app_painting_index') }}">Retour à la liste</a>

			</div>
		</div>

	</body>

{% endblock %}

templates/painting/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Painting index
{% endblock %}

{% block body %}

	<body class="homeImage">

		<h1 class="editTitle">Le tableau des tableaux</h1>

		<div class="alertContainer">
			<a class="btnAddPainting" href="{{ path('app_painting_new') }}">Ajouter une peinture</a>
		</div>

		<div class="alertContainer mb-5">

			<div class="sizeTableAdmin">

				<table class="table">
					<thead>
						<tr>
							<th>Painting_name</th>
							<th>PaintingURL</th>
							<th>PaintingDate</th>
							<th>PainterName</th>
							<th>PainterDescription</th>
							<th>actions</th>
						</tr>
					</thead>
					<tbody>
						{% for painting in paintings %}
							<tr>
								<td>{{ painting.paintingName }}</td>
								<td>{{ painting.paintingURL }}</td>
								<td>{{ painting.paintingDate }}</td>
								<td>{{ painting.painterName }}</td>
								<td>{{ painting.painterDescription }}</td>
								<td>
									<a href="{{ path('app_painting_show', {'id': painting.id}) }}">show</a>
									<a href="{{ path('app_painting_edit', {'id': painting.id}) }}">edit</a>
								</td>
							</tr>
						{% else %}
							<tr>
								<td colspan="8">no records found</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>

				<div class="alertContainer">
					<a class="btnAddPainting" href="/logout">Se déconnecter</a>
				</div>

			</div>
		</div>

	</body>

{% endblock %}

templates/painting/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer une nouvelle peinture
{% endblock %}

{% block body %}

	<body class="homeImage">

		<h1 class="editTitle">Créer une nouvelle peinture</h1>

		<div class="alertContainer">
			<div>

				{{ include('painting/_form.html.twig') }}
				<a class="returnText mt-3" href="{{ path('app_painting_index') }}">Retour à la liste</a>
			</div>
		</div>

	</body>
{% endblock %}

templates/painting/quizz.html.twig
{% extends 'base.html.twig' %}

{% block title %}Painting
{% endblock %}

{% block body %}

	{# <div id="painting-container"> #}
	{# <img src="Assets/starrynight.jpg" id="painting"> #}
	{# </div> #}
		<head><script src="https://code.jquery.com/jquery-3.6.0.min.js"> </script>
	</head>

	<main id="painting-container" class="paintingBG">
		<div class="alertContainer">
			{% if verificationResult == 'Correct answer!' %}
				<div class="alert alertSuccessQuizz alertQuizz">Bonne réponse !</div>
			{% elseif verificationResult == 'Wrong answer.' %}
				<div class="alert alertDangerQuizz alertQuizz">Mauvaise réponse !</div>
			{% endif %}
		</div>

		<div class="answersQuizz">

			<div class="guessQuizz">
				<h2 class="mt-3">
					<a data-bs-toggle="collapse" href="#screenGallery" role="button" aria-expanded="false" aria-controls="screenGallery" class="guessQuizz">JOUER</a>
				</h2>
			</div>

			<div class="collapse" id="screenGallery">
				<div class="row quizzForm">

					<h3 class="semiTitleQuizz">La peinture est :</h3>

					<form method="post">

						<div class="form-group">
							<label for="selectedAnswer"></label>
							<select class="form-control selectQuizz" id="selectedAnswer" name="selectedAnswer">
								<option value="" disabled selected hidden>Choissez une peinture</option>
								{% for painting in paintings %}
									<option value="{{ painting.paintingName }}" class="valueQuizz">{{ painting.paintingName }}</option>
								{% endfor %}
							</select>
						</div>

						<button type="submit" class="btnQuizz">Valider</button>
					</form>

					<button id="reset-button" class="resetBtn">Reset la position</button>

					<a class="navquizz" href="{{ path('app_painting_random') }}">
						<button type="button" class="btnSkip">Passer à un autre tableau ▶</button>
					</a>

				</div>
			</div>

		</div>

		<img src="{{ asset('build/images/' ~ painting.paintingURL) }}" id="paintingdrag" class=" animate__animated animate__fadeIn animate__slow">

	</main>
{% endblock %}

templates/painting/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Painting
{% endblock %}

{% block body %}


	<body class="homeImage">
		<h1 class="editTitle">{{ painting.paintingName }}</h1>

		<div class="alertContainer mb-5">

			<div class="sizeTableAdmin">

				<table class="table">
					<tbody>
						<tr>
							<th>Id</th>
							<td>{{ painting.id }}</td>
						</tr>
						<tr>
							<th>Painting_name</th>
							<td>{{ painting.paintingName }}</td>
						</tr>
						<tr>
							<th>PaintingURL</th>
							<td>{{ painting.paintingURL }}</td>
						</tr>
						<tr>
							<th>PaintingDate</th>
							<td>{{ painting.paintingDate }}</td>
						</tr>
						<tr>
							<th>PainterName</th>
							<td>{{ painting.painterName }}</td>
						</tr>
						<tr>
							<th>PainterDescription</th>
							<td>{{ painting.painterDescription }}</td>
						</tr>
						<tr>
							<th>SmallPaintingUrl</th>
							<td>{{ painting.smallPaintingUrl }}</td>
						</tr>
					</tbody>
				</table>

				<a class="btnAdminForm mt-3" href="{{ path('app_painting_edit', {'id': painting.id}) }}">Modifier</a>

				{{ include('painting/_delete_form.html.twig') }}

				<a class="returnText" href="{{ path('app_painting_index') }}">Retour à la liste</a>

			</div>
		</div>

	</body>
{% endblock %}